# Exercise - Rollback. 
# 
# 
AWSTemplateFormatVersion: 2010-09-09
Description: Blue / Green Testing
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: voltron-1
      ImageId: 'ami-0022f774911c1d690'
      InstanceType: t2.micro

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0