version: 2.1
orbs:
  circleci/aws-cli@2.0.3
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo " ** In work ** "

    create_infra:
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Running CF Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml
                --stack-name testing-stack-${CICLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  workflow:
    myWorkflow:
      jobs:
        - build
        - create_infra